name: Docker Image CI

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/git/Dockerfile --tag amarriner-gcp-git:${{ github.ref_name }}
