name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-image.yml'

env:
  DOCKER_IMAGE: amarriner-gcp-git
  DOCKER_TAG: latest
  GITHUB_USER_ID: '852892243405'
  GCP_PROJECT: operating-bolt-447818-b5
  GCP_REPO: amarriner-gcp-learning-repository
  GCP_REGION: us-east4

jobs:
  docker_build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auth to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'amarriner-workflow-sa@${{ GCP_PROJECT }}.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/${{ GITHUB_USER_ID }}/locations/global/workloadIdentityPools/amarriner-workload-pool/providers/amarriner-workload-pool-provider'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ GCP_PROJECT }}
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker us-east4-docker.pkg.dev
      - name: Build the Docker image
        run: |-
          docker build . --file docker/git/Dockerfile --tag "${{ GCP_REGION }}.pkg.dev/${{ GCP_PROJECT }}/${{ GCP_REPO }}/${{ DOCKER_IMAGE }}:${{ DOCKER_TAG }}"
          docker push "${{ GCP_REGION }}-docker.pkg.dev/${{ GCP_PROJECT }}/${{ GCP_REPO }}/${{ DOCKER_IMAGE }}:${{ DOCKER_TAG }}"

